cli/telepresence, docs/index.md
=> Detect remote Docker server and complain about it.

cli/telepresence, docs/index.md
=> Fix temporary directory on OS X.

Makefile, dev-requirements.txt, docs/index.md, local/entrypoint.py
=> Fix race condition in startup

cli/telepresence, docs/index.md, local/entrypoint.py
=> Better logic for finding pods.

cli/telepresence, docs/index.md, tests/test_run.py
=> Allow connections to localhost

docs/index.md, local/entrypoint.py, tests/test_dockerrun.py
=> Get env variables correctly in the face of multiple containers

ci/test.sh, cli/telepresence, docs/index.md, local/entrypoint.py, tests/disconnect.py, tests/test_run.py, tests/tocluster.py
Workaround, not quite a fix for #8, but better than nothing. Also fixes #24.
=> Disconnect when connection is lost, or proxy otherwise exits

cli/telepresence, dev-requirements.txt, docs/index.md, local/entrypoint.py, tests/test_run.py, tests/tocluster.py, tests/utils.py
=> Namespace support

cli/telepresence, docs/index.md
Fixes #84, at least partially.
=> Respect KUBECONFIG.

cli/telepresence, docs/index.md
=> Quick exit on errors

cli/telepresence
=> Complain if remote container doesn't have the same version as the local CLI

cli/telepresence, docs/index.md
=> Context flag support

docs/index.md, remote/Dockerfile
=> Work in the face of SSH compression

ci/test.sh, cli/telepresence
=> Ask if users wants to file an issue in --help.

cli/telepresence, docs/additional-information/changelog.md, remote/Dockerfile, tests/test_run.py, tests/utils.py
=> Resource limits

cli/telepresence, docs/additional-information/changelog.md
=> Fix and changelog.

cli/telepresence, docs/additional-information/changelog.md
=> Don't run .bashrc.

cli/telepresence, docs/additional-information/changelog.md
=> Better error messages for misconfigured Deployment.

cli/telepresence, docs/additional-information/changelog.md
Fixes #133.
Will finish this up tomorrow.
=> Always get context and namespace explicitly at startup.

cli/telepresence, docs/additional-information/changelog.md, remote/Dockerfile, remote/run.sh
=> Run Docker container as non-root user

Makefile, ci/test.sh, cli/telepresence, docs/additional-information/changelog.md, docs/user-guide/limitations-and-workarounds.md, tests/test_run.py, tests/unsupportedcli.py
=> Disable unsupported commands

cli/telepresence, docs/additional-information/changelog.md
=> Custom labeling

Makefile, ci/test.sh, cli/telepresence, docs/additional-information/changelog.md, docs/index.html, docs/user-guide/features-and-functionality.md, tests/test_run.py, tests/tocluster.py, tests/utils.py
=> OpenShift Origin support

cli/telepresence, docs/additional-information/changelog.md, tests/test_run.py, tests/tocluster.py, tests/utils.py
=> Option for swapping deployment

cli/telepresence, docs/_includes/getting-started-part-1.md, docs/_includes/getting-started-part-2.md, docs/_includes/head.html, docs/css/kissui.css, docs/css/pygments.css, docs/index.html, docs/reference/changelog.md, docs/tutorials/kubernetes.md, docs/tutorials/openshift.md, tests/test_run.py
=> Document openshift better

cli/telepresence, docs/reference/changelog.md
=> Missing context

docs/howto/golang.md
=> Minimal Go howto.

cli/telepresence, docs/reference/changelog.md
Based on patch from @drslump
`--verbose` and new logging of exit codes were tested manually.
Fixes #174.
=> Ignore local ssh config

cli/telepresence, docs/reference/changelog.md
=> Fix the regression in ping suppression

cli/telepresence
=> Drop filing-a-ticket in --help

cli/telepresence, docs/reference/changelog.md
=> Docker ip fetching fails

Makefile, cli/telepresence, docs/reference/changelog.md, docs/reference/methods.md, k8s-proxy/forwarder.py, tests/test_run.py
=> Sshuttle on minikube

ci/test.sh, cli/telepresence, docs/_includes/getting-started-part-2.md, docs/discussion/how-it-works.md, docs/howto/docker.md, docs/howto/golang.md, docs/reference/changelog.md, docs/reference/connecting.md, docs/reference/methods.md, docs/reference/proxying.md, docs/reference/running.md, docs/tutorials/kubernetes-client.md, docs/tutorials/kubernetes-rapid.md, docs/tutorials/openshift.md, tests/test_run.py, tests/utils.py
=> New deployment and vpn-tcp are now defaults

cli/telepresence, docs/reference/changelog.md
=> Usage examples

cli/telepresence, docs/reference/changelog.md, tests/test_run.py, tests/tocluster.py
=> Don't use local env variables with --docker-run.

docs/reference/changelog.md, k8s-proxy/forwarder.py, tests/tocluster.py
=> Curl dns broken

cli/telepresence, docs/reference/methods.md
=> Document limitations on startup.

cli/telepresence, docs/reference/changelog.md
=> Broken docker on OS X

Makefile, cli/telepresence, dev-requirements.txt, docs/reference/changelog.md, tests/telepresence.py, tests/test_run.py, tests/test_unit.py
=> Swap more parameters out in --swap-deployment

cli/telepresence, docs/reference/changelog.md, local-docker/entrypoint.py, packaging/build-sshuttle.py
=> Switch to newer, upstream sshuttle.

cli/telepresence, docs/reference/changelog.md, tests/test_run.py, tests/test_unit.py
=> Automatically expose ports when using --swap-deployment

cli/telepresence, docs/reference/changelog.md, k8s-proxy/Dockerfile, tests/envvariables.py, tests/test_run.py, tests/tocluster.py
=> Better method for getting env variables

k8s-proxy/Dockerfile
=> Switch to Alpine 3.6.

cli/telepresence
=> Tweak message.

.travis.yml, cli/telepresence, docs/reference/changelog.md, k8s-proxy/forwarder.py, local-docker/Dockerfile, packaging/build-sshuttle.py, packaging/create-linux-packages.py
Fixes #242.
Mostly this is fixed by LLMNR packet capture in sshuttle, but kept the DNS cache busting change since it's more robust way of doing things.
=> Fix systemd-resolved.

cli/telepresence, docs/reference/changelog.md, tests/test_run.py, tests/test_unit.py
=> Unbreak --swap-deployment.

cli/telepresence
This is the main repo version of #324.
=> Support deployments containing services of type ExternalName

docs/reference/developing.md
=> Use the recursive option.

docs/reference/community.md
=> add reference to abhishek article

ci/clean-cluster.py, docs/reference/changelog.md
Cleaned up the script a bit too. Note that we're using cascading deletes on namespaces for simplicity. If we see a reliability problem with this, we'll need to do something smarter.
=> Update the cluster cleanup script to nuke namespaces too

docs/index.html, docs/styles/home.css
=> Add Datawire logo to homepage header; New homepage quote

docs/SUMMARY.md, docs/case-studies/index.html, docs/case-studies/verloop.html, docs/index.html, docs/styles/home.css
Don't merge. Trying to get netlify deploy preview to run.
---
Before landing
=> initial version of verloop case study

tests/parameterize_utils.py
Previously hard-coded IP address got taken out of the rotation or
something and so the tests were invalid because they tried to talk to an
address which appears not to have had a server that wanted to talk to
us.
Fixes #476
=> Query for httpbin.org addresses on each run

tests/utils.py
=> fix typo in doc string

build, docs/reference/changelog.md, k8s-proxy/forwarder.py, k8s-proxy/resolver.py, k8s-proxy/test_forwarder.py, telepresence/vpn.py
=> Improve DNS suffix probe robustness

docs/reference/changelog.md, k8s-proxy/resolver.py
=> Quieter DNS failures

docs/case-studies/sight-machine.html, docs/styles/home.css
Add Sight Machine case study and case study index page
---
Before landing
=> Add case studies page [skip ci]

docs/reference/changelog.md, tests/conftest.py, tests/parameterize_utils.py, tests/test_endtoend.py, tests/test_run.py, tests/utils.py
=> Port swapdeployment tests to new testing framework

docs/reference/changelog.md, tests/conftest.py, tests/parameterize_utils.py, tests/probe_endtoend.py, tests/test_endtoend.py, tests/test_endtoend_distinct.py, tests/test_run.py
Last test to be ported for #400
=> Port test_disconnect

docs/reference/changelog.md, docs/reference/developing.md
Explains some of what happened for #400 to developers
=> Add documentation on end-to-end testing

docs/reference/changelog.md, telepresence/cleanup.py, telepresence/container.py, telepresence/deployment.py, telepresence/main.py, telepresence/remote.py, telepresence/runner.py, telepresence/vpn.py
This change modifies runner to track "spans" for making nested timing measurements as well as instrumenting the code to use these spans in various interesting places.
It also removes some redundant usages of the `*` operator in runner.py
---
Before landing
=> Runner spans

telepresence/runner.py
=> fix formatting of non-ended spans

docs/reference/developing.md, tests/conftest.py
=> End-to-end test suite pytest marks

docs/reference/changelog.md, local-docker/entrypoint.py
=> Make sure local docker route returns IP addresses

telepresence/main.py
=> Pass all the forward args to one ssh process.

k8s-proxy/resolver.py
Fixes #192 
master behavior:
> $ telepresence --method vpn-tcp        
> Starting proxy with method 'vpn-tcp', ...                                                                 
> Volumes are rooted at ...
> 
> No traffic is being forwarded ...
> 
> [sudo] password for exarkun:                   
> @gke_datawireio_us-central1-a_telepresence-testing|(virtualenv) $ host kubernetes
> kubernetes.local has address 10.3.240.1
> kubernetes.local has address 10.3.240.1
> Host kubernetes.local not found: 3(NXDOMAIN)
> @gke_datawireio_us-central1-a_telepresence-testing|(virtualenv) $ 
> 
branch behavior:
> $ TELEPRESENCE_REGISTRY=exarkun TELEPRESENCE_VERSION=0.78-4-g3409ce0-LNX-1522412298 telepresence --method vpn-tcp                                  
> Starting proxy with method 'vpn-tcp', ...
> …
=> Replace suffix stripping with fast NXDOMAIN.

docs/reference/changelog.md, telepresence/cli.py, telepresence/main.py, telepresence/runner.py
- Capture more data in crash (fixes #446)
- Make it clear that crash data is not submitted automatically
- Catch the end of the log file on crash (fixes #466)
=> Crash reporter

k8s-proxy/resolver.py, newsfragments/578.bugfix
This reverts commit dee1fdeb42f677fc8779c2153f477cdd6ecced40.
Fixes #578
=> Revert "Replace suffix stripping with fast NXDOMAIN."

docs/reference/connecting.md, docs/reference/developing.md, newsfragments/568.bugfix, telepresence/deployment.py, telepresence/runner.py
=> WIP: Narrow required cluster permissions

build, telepresence/cache.py, telepresence/cleanup.py, telepresence/ssh.py, telepresence/vpn.py
=> Make sure source files have the Apache license header

MAINTAINERS.md
=> i forgot how markdown works [ci skip]

.circleci/config.yml, dev-requirements.txt, install.sh, packaging/build-sshuttle.py, packaging/build-telepresence.py, packaging/container.py, packaging/deploy.py, packaging/distros.py, packaging/package_linux.py, telepresence/usage_tracking.py
=> Make Telepresence a single-file executable and build packages in one container

newsfragments/672.bugfix, telepresence/container.py
=> Use sudo -E docker instead of sudo docker for the user's container

GOVERNANCE.md, MAINTAINERS.md
=> Add governance document [ci skip]

.towncrier/template.md, docs/build-website.py, docs/reference/developing.md, newsfragments/682.bugfix, packaging/build-telepresence.py, packaging/deploy.py, packaging/homebrew-formula.rb, packaging/homebrew-package.sh
=> Release fixes

.circleci/config.yml, local-docker/entrypoint.py, packaging/package_linux.py, telepresence/cache.py, telepresence/cleanup.py, telepresence/cli.py, telepresence/container.py, telepresence/deployment.py, telepresence/local.py, telepresence/main.py, telepresence/mount.py, telepresence/proxy.py, telepresence/runner.py
Make cleanup go through the runner instead of using atexit
=> Testable cleanup

local-docker/entrypoint.py, telepresence/cleanup.py, telepresence/expose.py, telepresence/mount.py, telepresence/proxy.py, telepresence/remote_env.py, telepresence/runner.py, telepresence/vpn.py
Make output to the user go through the runner instead of using print.
In service of #628 and #572.
=> Testable output

newsfragments/713.bugfix, telepresence/cache.py
=> Don't crash in the presence of an empty or corrupted cache file

docs/reference/install.md, newsfragments/278.bugfix, telepresence/container.py, telepresence/deployment.py, telepresence/expose.py, telepresence/local.py, telepresence/mount.py, telepresence/proxy.py, telepresence/remote.py, telepresence/runner.py, telepresence/startup.py, telepresence/vpn.py, tests/utils.py
Adds an explicit `sudo` warning to partly address #262.
Addresses the `isatty` item from #572.
Fixes #278.
Fixes #306.
In service of #628.
=> Testable various

docs/case-studies/engel-volkers.html, docs/case-studies/index.html, docs/styles/home.css
- Add Engel & Volkers Case Study to /case-studies
- Alpha order case studies
- Fix Broken Link in Engel & Volkers Case Study
---
=> Add Engel & Volkers Case Study [CI Skip]

newsfragments/750.bugfix, telepresence/cli.py, telepresence/runner/__init__.py
=> Fix local container crash

README.md, ci/release-in-docker.sh, docs/SUMMARY.md, docs/about.html, docs/case-studies/bitnami.html, docs/case-studies/engel-volkers.html, docs/case-studies/index.html, docs/case-studies/iris-tv.html, docs/case-studies/sight-machine.html, docs/case-studies/verloop.html, docs/index.html, docs/macros.html, docs/reference/community.md, docs/reference/developing.md, docs/reference/proxying.md, docs/reference/upgrade.md, telepresence/cli.py
=> Change Gitter references to Slack

build, packaging/build-sshuttle.py, packaging/build-telepresence.py, packaging/deploy.py, packaging/homebrew-formula.rb, packaging/homebrew-package.sh
Fixes #758. This may help with weird installation issues like #754.
=> Update Brew packaging to use same installable artifacts as the Linux packages

newsfragments/460.misc, telepresence/startup.py
this is a fix for #460
Signed-off-by: rohan47 <rohanrgupta1996@gmail.com>
(Re-submitting this PR so CI will run)
=> fix: Crash on `sudo telepresence`

README.md
=> Add details about usage reporting to readme

newsfragments/787.bugfix, telepresence/startup.py
=> Add context argument to namespace check.

docs/reference/developing.md
updated git repo url in developing doc
=> updated git repo url in developing doc

tests/parameterize_utils.py, tests/utils.py
=> Launch existing deployment with the correct image

docs/about.html, docs/case-studies/bitnami.html, docs/case-studies/engel-volkers.html, docs/case-studies/index.html, docs/case-studies/iris-tv.html, docs/case-studies/sight-machine.html, docs/case-studies/verloop.html, docs/index.html
Merge this when kubecon is over and you want to remove the announcement banner.
=> Remove kubecon announcement

newsfragments/783.bugfix, telepresence/connect/ssh.py, telepresence/mount.py, telepresence/outbound/container.py, telepresence/outbound/vpn.py
=> Replace localhost with 127.0.0.1

newsfragments/592.bugfix, newsfragments/756.bugfix, telepresence/proxy/deployment.py, telepresence/proxy/remote.py, telepresence/runner/runner.py
Fixes #592 
Fixes #756 
Fixes #820
=> Deal with deployment checks for -n and -d operations

newsfragments/426.bugfix, telepresence/startup.py
=> Output a warning if cluster and client versions differ greatly

telepresence/outbound/vpn.py
- Don't use a subprocess
- Make to see more than one success
- Also resolve a dotted name that should end up in the logs
Fixes #764  
Fixes #833
=> Replace sshuttle startup loop with something more sensible

newsfragments/876.misc, packaging/distros.py
=> Add Ubuntu Cosmic and Fedora 29

docs/macros.html
"background" -> "foreground" (`fg`, brings the process
to the foreground).
=> Minor fix to doc for local debugging

docs/discussion/how-it-works.md, newsfragments/736.bugfix, telepresence/startup.py
=> Detect docker desktop

newsfragments/235.bugfix, telepresence/connect/connect.py, telepresence/connect/expose.py, telepresence/outbound/container.py, telepresence/outbound/local.py, telepresence/proxy/deployment.py
=> Emit additional useful output to the user

docs/tutorials/docker.md
"diretory" to "directory" in line 59.
=> Fix misspell in docker.md

telepresence/_version.py, versioneer.py
"Eexceptions" to "Exceptions".
=> Fix some typos in code

docs/tutorials/docker.md
QotM no longer supports live updates, so I replaced it with something much simpler that does.
[ci skip]
=> Fix the Docker (primary) tutorial

newsfragments/1037.feature, telepresence/proxy/__init__.py, telepresence/proxy/deployment.py
=> fix: Add deploymentconfig support to --deployment

newsfragments/1054.bugfix, telepresence/outbound/setup.py
=> Run an iptables smoke test to catch running in an unpriv container

telepresence/outbound/setup.py, tests/cluster/test_endtoend.py
=>  Apply also-proxy tests only to the vpn-tcp method

telepresence/outbound/vpn.py
=> Log some stuff that may help diagnose vpn-tcp method failures

newsfragments/1093.feature, telepresence/cli.py, telepresence/proxy/__init__.py, telepresence/proxy/deployment.py, tests/local/test_unit.py
Fixes #1093 
Based on #1067 and #1098
=> Allow setting the service account

newsfragments/1000.bugfix, newsfragments/1075.bugfix, newsfragments/873.bugfix, telepresence/connect/connect.py, telepresence/connect/ssh.py, telepresence/outbound/local.py, telepresence/outbound/setup.py, telepresence/proxy/__init__.py, telepresence/proxy/deployment.py, telepresence/startup.py, telepresence/utilities.py
Fixes #873 
Fixes #1000 
Fixes #1075
=> Fix some small bugs

newsfragments/1118.feature, telepresence/outbound/local.py
Fixes #1118
If there is a better way to implement this, please point me to it, I would be more than happy to implement it.
=> Flush DNS cache after connecting on MacOS clients

newsfragments/379.bugfix, telepresence/outbound/vpn.py, tests/cluster/parameterize_utils.py, tests/cluster/utils.py, tests/local/test_unit.py
An attempt at solving #379 :)
disclaimer: I'm not a python dev :D
=> resolve and proxy all ips for a given hostname when using --also-proxy

telepresence/runner/launch.py, telepresence/runner/runner.py
I've submitted a few PRs this week and all of them failed CI due to these lint errors. I finally took the time to figure out how to fix them. Not sure how the errors crept in to master though. Is the version of mypy floating such that a newer and stricter release got pulled in automatically?
=> Fix mypy lint errors

docs/USERS.md
---
```shell
```
- You can preview the changelog with
```shell
virtualenv/bin/towncrier --draft
```
- Please delete this …
=> Update Telepresence user report 

newsfragments/1297.bugfix, telepresence/proxy/__init__.py, telepresence/proxy/deployment.py
=> CI for PR 1312

telepresence/outbound/vpn.py
Basically #1304 plus an error check. Doing this myself for expediency.
=> Smarter Pod CIDR detection (cf #1304)

newsfragments/1305.feature, telepresence/proxy/deployment.py
Do what #1306 does, but with more control.
=> Add support for the TELEPRESENCE_USE_OCP_IMAGE env var

newsfragments/1356.bugfix, telepresence/proxy/deployment.py, tests/cluster/conftest.py, tests/cluster/parameterize_utils.py, tests/cluster/test_endtoend.py, tests/cluster/test_endtoend_distinct.py
=> fix: auto expose ports for existing Deployment*

docs/case-studies/index.html
---
```shell
```
- You can preview the changelog with
```shell
virtualenv/bin/towncrier --draft
```
- Please delete this …
=> Updated casestudy logos

newsfragments/1041.feature, telepresence/proxy/manifest.py, telepresence/proxy/operation.py, telepresence/proxy/proxy.py, telepresence/proxy/remote.py, telepresence/startup.py, tests/cluster/test_endtoend.py, tests/cluster/utils.py
Implements https://github.com/telepresenceio/telepresence/issues/1041#issuecomment-635537160
I'm going to put off these tasks for a future issue/PR
=> Proxy as a Pod

telepresence/outbound/cidr.py
=> outbound: Add missed CalledProcessError check in cidr.py

packaging/distros.py
Remove Ubuntu Eoan, as that is breaking packaging.
Add Ubuntu Groovy and Fedora 33.
=> Update Linux distributions

.circleci/config.yml, environment-setup.sh, tests/cluster/parameterize_utils.py, tests/cluster/probe_endtoend.py, tests/cluster/test_endtoend.py
Resolve #1455 by turning off volume mounts in MacOS CI
=> Fix MacOS CI

ci/setup-gcloud.sh
The failing command doesn't appear to _need_ to succeed...
=> ci: Try to avoid the gcloud failure with the latest gcloud

telepresence/main.py, telepresence/outbound/local.py, telepresence/runner/runner.py
The work done in #1183 is defunct. I've reclaimed the first two commits here so that work isn't lost. The rest is dead.
=> Reclaim work from the method-teleproxy branch

docs/community.html, docs/reference/upgrade.md
---
```shell
```
- You can preview the changelog with
```shell
virtualenv/bin/towncrier --draft
```
- Please delete this …
=> Update community page

docs/reference/changelog.md, docs/reference/upgrade.md
---
```shell
```
- You can preview the changelog with
```shell
virtualenv/bin/towncrier --draft
```
- Please delete this …
=> Include information on how to try Telepresence 2

LICENSE, README.md
Bjorn asked me this morning if there was a LICENSE file, and I said I was pretty sure there was.  But I was mistaken!
=> [v2] Add a LICENSE file, remove "internal" line from the README

README.md
Update README with more context on TP2.
=> update with some context

smoke-tests/run_smoke_test.sh
Fixing up part of smoke tests that broke with new features + some overall cleanup
```shell
```
- You can preview the changelog …
=> [v2] Fixing smoke tests

pkg/client/cli/intercept_state.go, pkg/client/cli/list.go, pkg/client/cli/preview.go
Signed-off-by: Thomas Hallgren <thomas@datawire.io>
=> Improve how prerequisites for remote volume mounts are reported.

CHANGELOG.md, go.mod, pkg/client/connector/install.go, pkg/client/connector/install_actions.go, pkg/client/connector/install_test.go, pkg/client/connector/testdata/addAgentToDeployment/mp-tc-1.input.yaml, pkg/client/connector/testdata/addAgentToDeployment/mp-tc-1.output.yaml
I just want to say: Woohoo, the PR template worked.
=> v2.1.1 release branch

cmd/traffic/cmd/agent/forwarder.go, smoke-tests/run_smoke_test.sh
1. Improve some error message clarity in the dumb agent
2. Fix `run_smoke_test.sh` on GNU/Linux
3. Have slightly better diagnostic output from  `run_smoke_test.sh`
As usual, I suggest a commit-by-commit review.
=> [v2] Misc fixup, take 3

pkg/client/cli/update_check.go
Signed-off-by: Kenn Hussey <kennhussey@datawire.io>
Updating the upgrade documentation link to point to the new location.
=> [v2] Update upgrade link

cmd/traffic/cmd/manager/internal/test/load_testdata_internal.go, go.mod, pkg/client/config.go, pkg/client/connector/intercept.go, pkg/client/connector/k8s_cluster.go, pkg/client/connector/service.go, pkg/client/connector/traffic_manager.go
This PR contains some improvements to the config parser and how timeouts are handled.
=> [v2] Improve config.yml parser and timeout handling.

CHANGELOG.md, cmd/traffic/cmd/manager/internal/test/load_testdata_internal.go, go.mod, pkg/client/config.go, pkg/client/connector/intercept.go, pkg/client/connector/k8s_cluster.go, pkg/client/connector/service.go, pkg/client/connector/traffic_manager.go
=> Prepare v2.1.2

pkg/client/connector/install.go, pkg/client/connector/install_actions.go
@thallgren Remember back in December when I had a PR that had 1 commit in it that made a whole bunch of hard-to-follow cleanup changes to `install_actions.go`, and we agreed I'd remove it from that PR?  This PR is all of those cleanup changes, but split out in to separate commits and hopefully justified in comments and commit messages.
I do suggest a commit-by-commit review.
=> [v2] Improve install_actions.go

CHANGELOG.md, go.mod
Signed-off-by: Luke Shumaker <lukeshu@datawire.io>
A few sentences describing the overall goals of the pull request's commits.
=> Prepare v2.1.3

CHANGELOG.md
@leoluz informs me that the issue in the changelog has to do with Argo Rollouts, not Argo CI.
=> CHANGELOG: 2.1.3: Argo Rollouts, not Argo CD

pkg/client/cli/update_check.go
Signed-off-by: Kenn Hussey <kennhussey@datawire.io>
Updating the upgrade link to the latest URL.
=> [v2] Update upgrade link to latest

cmd/traffic/cmd/manager/internal/watchable/generated_agentmap.go, cmd/traffic/cmd/manager/internal/watchable/generated_clientmap.go, cmd/traffic/cmd/manager/internal/watchable/generated_interceptmap.go, cmd/traffic/cmd/manager/internal/watchable/generic.tmpl.go, go.mod, pkg/client/auth/login.go, pkg/client/auth/login_test.go, pkg/client/auth/logout.go, pkg/client/auth/pkce.go, pkg/client/cache/cache.go, pkg/client/cli/auth.go, pkg/client/cli/command.go, pkg/client/cli/dashboard.go, pkg/client/cli/intercept_state.go, pkg/client/cli/preview.go, pkg/filelocation/borrowed_os_file.go, pkg/filelocation/os_file_test.go
- The first commit is me noticing and fixing something that the linter should catch, but doesn't catch for dumb reasons.
- The second commit is fixing an issue with `pkg/filelocation` that allowed me to write a broken test that passed on my laptop but not in CI.
- The third commit is making an improvement to `pkg/client/cache` that I noticed while identifying the `pkg/filelocation` issue.
- The final 8 commits are some generic cleanup in `pkg/client/auth`.
=> [v2] Pt1: Misc auth cleanup

pkg/client/connector/auth/login.go
What it says in the title.  This is a regression in 2.1.4-rc.0; no need for a changelog entry.
=> [v2] Fix nil-pointer panic after logout

CHANGELOG.md, go.mod, pkg/client/cli/cliutil/systema.go, pkg/client/cli/telepresence_test.go, pkg/client/connector/auth/login.go, pkg/client/logging/initcontext.go, pkg/client/logging/rotatingfile.go
=> Releasing 2.1.4

DEVELOPING.md
Add some notes to DEVELOPING.md about the tricks I used to debug #1640.
=> DEVELOPING.md: Add a note about debugging early setup

MEETING_SCHEDULE.md
Signed-off-by: Kenn Hussey <kennhussey@datawire.io>
This pull request adds a markdown file containing information about our community meetings.
=> [v2] Adding meeting schedule

CHANGELOG.md, pkg/client/connector/install.go, pkg/client/connector/install_actions.go, pkg/client/connector/testdata/addAgentToWorkload/deployment-initializer.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-mp-tc-0.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-mp-tc-1.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-mp-tc-2.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-mp-tc-3.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-0.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-1.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-10.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-11.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-2.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-3.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-4.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-5.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-6.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-7.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-8.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-9.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/replicaset-mp-tc-0.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/replicaset-tc-0.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/statefulset-mp-tc-0.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/statefulset-tc-0.output.yaml
Well, rather: Add the necessary stubs for the smart agent to implement mTLS.
Unfortunately, I didn't write any automated tests
=> [v2] Add mTLS support to --mechanism=http

CHANGELOG.md, go.mod, pkg/client/connector/install.go, pkg/client/connector/install_actions.go, pkg/client/connector/testdata/addAgentToWorkload/deployment-initializer.input.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-initializer.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-mp-tc-0.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-mp-tc-1.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-mp-tc-2.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-mp-tc-3.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-0.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-1.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-10.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-11.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-2.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-3.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-4.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-5.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-6.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-7.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-8.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-9.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/replicaset-mp-tc-0.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/replicaset-tc-0.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/statefulset-mp-tc-0.output.yaml, pkg/client/connector/testdata/addAgentToWorkload/statefulset-tc-0.output.yaml
A few sentences describing the overall goals of the pull request's commits.
=> [v2] Release v2.1.5

smoke-tests/run_smoke_test.sh
This PR removes edge stack from the smoke tests which makes it faster,
as well as doesn't make us depend on a loadbalancer type service to
smoke test telepresence.  Additionally, this matches what is used in our
quick start, so all-in-all a much better smoke test
Signed-off-by: Donny Yung <donaldyung@datawire.io>
---
=> Improve smoke tests

telepresence/connect/connect.py
Fixed type hinting for setup method's return type, from generic Callable, to be more specific.
=> fixed type hinting for setup method's return type to be more specific
