telepresenceio/telepresence

- local/entrypoint.py
The deployment's podspec metadata doesn't necessarily have a namespace.
This is untested because it looks like actually testing it would be tricky.
> get the deployment's namespace for filtering pods

- cli/telepresence
Solves https://github.com/datawire/telepresence/issues/174
Additionally there are some improvements for troubleshooting by enabling verbose logging on ssh and kubectl with the `--verbose` flag.
> Ignore local ssh config

- packaging/Dockerfile.alpine
- packaging/build-package.sh
- packaging/create-linux-packages.py
- packaging/upload-linux-packages.py
Builds client .apk packages for Alpine Linux 3.5 and 3.6. This distro is very popular for containers given it's small footprint.
The publishing/uploading hasn't been tested but hopefully it works straight away 😳 
Note that for building on Alpine it first generates a local image with the FPM requirement.
> Alpine Linux apk packages

- cli/telepresence
PR to fix #202 
I improved docker0 ip fetching in couple ways:
- try first to use `ip addr` instead of deprecated `ifconfig
- Fixed regex so that it works on each version of ifconfig
- Throw error if telepresence was unable to get ip for docker0
> Enhance docker0 ip address fetching

- docs/reference/upgrade.md
Gitbook uses nunjucks for templating, for some reason it struggles with certain html
> Fix templating error on updating telepresence page

- cli/telepresence
- k8s-proxy/forwarder.py
- tests/test_unit.py
This is the main repo version of #313.
> Add support for deployments using `automountServiceAccountToken: false`

- build-linux.sh
- ci/push-images.sh
- ci/setup-gcloud.sh
This is a *step* towards #374.  It lays out a plan:
```
```
and accomplishes the first step.
> Some generalization of build-linux.sh

- telepresence/deployment.py
- tests/test_run.py
Fixes #427 
Basically a revert of #420 plus a little better failure reporting for some tests.  Doesn't entirely make sense to me unless we buy "Kubernetes bug" as an explanation.  But CI says this is much more reliable, so ...
> Reduce frequency of test_swapdeployment failures

- .circleci/config.yml
- build
This way lint failures don't interrupt the test suite runs.
Broken off the #400 branch to try to get it to a more manageable size.
> Promote linting to its own job

- .circleci/config.yml
- .travis.yml
- build
- docs/reference/developing.md
Stacked on top of #432 so review that first.
Removes the Travis configuration for running any of the test suite.  Also removes supporting build script code.  The release bits remain in the Travis configuration as CircleCI is not yet configured for that part.
Broken off of the #400 branch to try to make it a more manageable size.
> Disable travis linux testing

- build
Original integration tests had `SCOUT_DISABLE` set but the new ones were missing it.
> Set SCOUT_DISABLE for both kinds of tests

- tests/parameterize_utils.py
- tests/probe_endtoend.py
- tests/test_endtoend.py
- tests/test_run.py
Step towards completing #400 
I haven't updated changelog.  Seems like it might not  be useful to do that for each individual test we port.  Probably worth a mention when everything has been ported, though?
> Port test_loopback to test_endtoend

- .circleci/config.yml
The CircleCI configuration tells the Linux job  to run the test suite twice, accidentally.
> Avoid tests during Linux env setup

- docs/reference/limitations.md
Docs for  #464
Assuming I don't need to update the CHANGELOG for documentation changes?
> Document workaround for --docker-run & firewalld

- tests/parameterize_utils.py
- tests/probe_endtoend.py
- tests/test_endtoend.py
- tests/test_run.py
Another step towards #400 
Apart from porting some tests that exercise network traffic from Telepresence execution context to the Kubernetes cluster, this also introduces a long-running probe process.  The probe process now keeps running from before the first test that needs its particular config until after the last test is done.  This allows the tests to interact with the process which facilitates some of the tests ported here (for example, retrieving the environment from the probe and using it to construct a url to ask the probe to retrieve, then checking the result of that operation).
> Port "tocluster" tests from test_run to test_endtoend

- telepresence/cli.py
- tests/parameterize_utils.py
- tests/test_run.py
- tests/test_unit.py
Another step towards #400.
These tests don't need to be end-to-end.  They're just argparser unit tests.
> Port some argument parsing tests

- telepresence/deployment.py
- tests/parameterize_utils.py
- tests/utils.py
Fixes #511 
Each run of `test_endtoend.py` will now select different "remote" ports (ie `hostPort`\ s).  This will prevent concurrent test runs from wanting to have a Kubernetes node bind the same port number.  Since there are only a handful of Kubernetes nodes and each can only bind any given port number once, this will avoid the unnecessarily tight bottleneck of only being able to have a handful of concurrent test runs.  It also makes the Kubernetes pod scheduler's job a little easier which I guess is a good thing.
This also includes a change to include the hostname where the test suite is running in the randomly generated names.  I found this helpful for filtering out Kubernetes resources that belonged to _my_ test runs when inspecting the cluster.
This also includes a change to make …
> Randomize the hostPorts used by the end-to-end test suite

- docs/reference/changelog.md
- local-docker/entrypoint.py
> Increase container networking timeout (fixes #340 and #539)

- telepresence/runner.py
> Avoid race condition in subprocess capture

- docs/tutorials/docker.md
This commit fixes a typo, replaces "workding" with "working"
> Fix typo in word workding

- telepresence/remote.py
- telepresence/runner.py
... so that the output can be used in error messages if a command fails.
---
> Populate CalledProcessError with command output

- docs/reference/community.md
> add Ironclad post to community page

- docs/index.html
- docs/styles/home.css
> Show kubecon announcement

- docs/index.html
> Remove kubecon banner

- docs/case-studies/iris-tv.html
- docs/styles/home.css
> Add iris tv case study

- newsfragments/587.bugfix
- telepresence/deployment.py
- tests/test_unit.py
> Strip out pod lifecycle hooks in swap-deployment. Fixes #587

- docs/case-studies/bitnami.html
- docs/case-studies/index.html
- docs/styles/home.css
> Add Bitnami and Ironclad case studies

- tests/parameterize_utils.py
Each probe runs telepresence once, then communicates with that process
to make assertions about what telepresence has done. The first test in
each probe sequence is what prompts the test system to run telepresence.
If that first attempt fails, each subsequent test in the same probe
fruitlessly tries to run telepresence again. This change makes those
subsequent tests fails immediately.
Fixes #653
---
E.g., `532.bugfix` would contain the text "Telepresence should no longer get confused looking for the route to …
> WIP: Make failures quicker in end-to-end tests

- telepresence/cleanup.py
- telepresence/mount.py
- telepresence/proxy.py
- telepresence/remote.py
- telepresence/remote_env.py
- telepresence/runner.py
- telepresence/startup.py
- telepresence/vpn.py
- tests/utils.py
> Testable exit

- telepresence/cli.py
- telepresence/main.py
- telepresence/runner.py
- tests/test_endtoend.py
Make cleanup and crash reporting go through context managers instead of using decorator and atexit magic.
In service of #628.
> Testable crash handling

- docs/tutorials/intellij.md
> [WIP] Create Telepresence IntelliJ tutorial

- docs/_layouts/website/page.html
- docs/js/datawire-breadcrumb.js
- docs/styles/website.css
> Add conditional links back to datawire

- newsfragments/738.bugfix
- telepresence/outbound/__init__.py
> Fix the `bash--norc` typo introduced in 0.91

- newsfragments/330.bugfix
- telepresence/startup.py
> Print a happy little error msg instead of traceback

- newsfragments/460.misc
- telepresence/startup.py
This is a fix for #460
Previously while running `sudo telepresence` gave the following output
```
T: No current-context set. Please use the --context option to explicitly set the context.
```
which did not mention that `kubectl` subprocess is looking at root's Kubernetes configuration instead of that of the user.
So after this enhancement, it will detect we are running as root and will suggest user to not use sudo
Signed-off-by: rohan47 <rohanrgupta1996@gmail.com>
---
E.g., `532.bugfix` would contain the text …
> fix: Crash on `sudo telepresence`

- docs/styles/home.css
Hubspot changed their dom structure on embedded forms, this pr addresses the broken styling because of the change.
---
> Fix hubspot embed form

- newsfragments/781.bugfix
- telepresence/startup.py
fixes #781. Somewhere between 6b793 and 407ba the call to check if in local vm moved from final checks inside KubeInfo instantiation, whereas runner.kubectl is the final output of KubeInfo instantiation.
> Fix call to uninstantiated KubeInfo

- docs/discussion/overview.md
Looks like the three links on the overview page are broken, here is the fix.
> Fixed the broken links on overview page

- .circleci/config.yml
- .dockerignore
- .gitignore
- Makefile
- dev-requirements.txt
- environments/.gitignore
- environments/archlinux.mkosi
- environments/archlinux.postinst
- environments/archlinux.pre-run
- environments/debian.mkosi
- environments/debian.postinst
- environments/debian.pre-run
- environments/fedora.mkosi
- environments/fedora.postinst
- environments/fedora.pre-run
This PR
- Adds the `make testbench-check` target, which is like `make check`, but runs `make check` in [testbench](https://github.com/datawire/testbench)
- Adds several simple testbench environments
- Adds a CircleCI job to run `make testbench-check`
At this time, I 100% expect CI to come back and tell me I did everything wrong, hence [WIP].
> Run testsuite in testbench

- newsfragments/869.bugfix
- telepresence/outbound/local.py
- telepresence/outbound/setup.py
- telepresence/runner/runner.py
> Make PATH and dependency fixes

- .gitattributes
- No one will ever want to use a regular text diff on them
- No one will ever want them to show up in `git grep`
I'm tired of having to type `-- ':!*.min.js'` to exclude these every time I run `git grep`.
> .gitattributes: Mark *.min.js files as "binary"

- packaging/retrieve-teleproxy.py
- telepresence/outbound/command.py
- telepresence/runner/runner.py
This modifies `telepresence outbound` to wait for teleproxy to send READY=1 over the sd_notify(3) interface during start-up.  It assumes that https://github.com/datawire/teleproxy/pull/33 will be present in teleproxy 0.3.6, and that 0.3.6 will be released by the time the next telepresence release is cut.
This has been tested on Parabola, and on macOS 10.13.6.
> Avoid teleproxy startup race

- Makefile
Alternatively, we could lock down to pip 18.1 which worked by adding:
```
$(PIP) install pip==18.1
```
Fixes #902
> fix(#902): disables pep517 while installing root deps

- telepresence/proxy/deployment.py
This PR improves usage of Telepresence with OpenShift. 
Potentially fixes: #299 #581 #582 #663 #666 #793 #825 
While using telepresence with Openshift (v3.11.0) I came across several problems.
Current version calls `server + '/version/openshift'` which returns 404 thus the code concludes it needs to use `kubectl` instead of `oc`. 
See d1817c1.
As OpenShift support both `DeploymentConfig` and `Deployment` resources we have to check which is used in the current namespace for `--swap-deployment` mode before proceeding.  
See 1b12fc5.
Current implementation attempts to swap `ReplicationController`, but if deployment config has `ImageStream` trigger this will result with discarding telepresence deployment and roll back to original one.
See b48ff8a.
> fix: OpenShift Deployment/DeploymentConfig support

- docs/discussion/how-it-works.md
- newsfragments/736.bugfix
- telepresence/startup.py
Docker Desktop has the same issue as minikube/minishift, so we need to
detect and handle it the same way.
Fixes #736.
> Fix outbound network access with Docker Desktop

- Makefile
- docs/SUMMARY.md
- docs/reference/developing.md
- docs/tutorials/openshift.md
* mentions adding security context constraints for the user when using OpenShift
* creates doc-related targets in Makefile
* minor polishing in dev guide with mention how to run docker registry locally (useful when building)
> Openshift docs

- docs/tutorials/java.md
- newsfragments/955.misc
The Maven option in current doc only works for JDK 9+.
I added a substitute option for JDK 5-8. (Thanks for @ark3)
Closed #955
> [#955] Add Maven Option of Local Java Deployment Tutorial for JDK under 9

- newsfragments/967.bugfix
- telepresence/proxy/remote.py
> version split allows for private registries

- newsfragments/929.bugfix
- telepresence/proxy/deployment.py
By using `oc rollout status -w dc/name` we can wait during cleanup process until original deployment config is restored, finishing Telepresence process at the right moment.
Fixes #929
> fix(openshift): waits for original deployment config to be available

- docs/howto/volumes.md
- k8s-proxy/podinfo.py
- newsfragments/917.feature
- telepresence/remote_env.py
- tests/test_endtoend.py
Proposed solution to #917.
I've recently discovered telepresence, and quickly got hooked.  I have a whole bunch of micro-services running on k8s, each with a different list of volume mounts.  Instead of having to manually create sym-links or use `proot` to create fake bindings, what I really want is to be able to get a list of mounts from telepresence, which I can then use to automatically handle the mounts.
This pull request adds a `TELEPRESENCE_MOUNTS` environment variable to the local container that holds a colon-separated list of remote mount points, ignoring those that docker automatically creates (`/sys/*`, `/proc/*`, `/dev/*`, `resolv.conf`, `hostname`, `hosts`).
With this in hand, a manually-updated list of locations that must be sym-link'd or bind-mount'd from under …
> Add env var for remote volume mounts as colon-seperated list

- newsfragments/966.bugfix
- telepresence/connect/connect.py
- telepresence/mount.py
- telepresence/proxy/__init__.py
- telepresence/proxy/deployment.py
- telepresence/proxy/remote.py
- telepresence/runner/launch.py
- telepresence/runner/runner.py
- telepresence/startup.py
Now synchronous subprocess calls (`runner.get_output(...)` and `runner.check_call(...)`) use almost the same code. They always capture stderr and have it available for reporting to the user upon failure. There is no longer any need to use get_output and throw away the answer just to have stderr around for error reporting.
Fixes #966
> Improve sync subprocesses

- newsfragments/598.bugfix
- telepresence/connect/connect.py
- telepresence/runner/runner.py
so that Telepresence no longer quits if its `kubectl logs` subprocess quits.
Fixes #598 
Fixes #916 
Fixes #969
>  Make kubectl logs a non-critical subprocess 

- newsfragments/986.bugfix
- telepresence/outbound/vpn.py
- telepresence/runner/runner.py
- tests/test_unit.py
>  Put a timeout on vpn-tcp startup loop DNS lookups to avoid a DNS hang breaking session startup

- newsfragments/1003.bugfix
- telepresence/runner/runner.py
This fixes [bug 1003](https://github.com/telepresenceio/telepresence/issues/1003). 
I added a [detailed comment](https://github.com/telepresenceio/telepresence/issues/1003#issuecomment-485592803) that explains the issue + sample code that demonstrates it.
This change was tested successfully by on macOS by attaching the Goland (delve) debugger to a Go service and the Pycharm debugger to a Python service. Before this change attaching a debugger would cause telepresence to incorrectly assume the process exited and shutdown.
> Add support for attaching a debugger to processes under telepresence

- k8s-proxy/Dockerfile
- k8s-proxy/pre-run.sh
- newsfragments/1013.bugfix
This an attempt to address #1013, at least in the common cases.
> Switch to telepresence user if unpriv running as root

- telepresence/outbound/local.py
It seems more are facing the same "google.com" problem, starting with #389 ( #1071 and others).
It's understood that it takes more time to make test network connection optional, or more configurable.
This a PR for an already suggested option, which might solve most (if not all) current real case scenarios where there is no internet connection.
While there might be some network policies blocking kubernetes.default.svc:443, those cases most probably won't have internet access either, therefore this proposal can be seen as a small first step in fix direction.
PS: It us agnostic to k8s flavour, therefore good also for OCP.
> PR for prev. solution in #389 (no google.com)

- telepresence/startup.py
Docker Desktop for Mac has changed the context name it uses. I added a check for this new context name next to docker-for-desktop in startup.py. I wonder if there is a better way to check if telepresence is running locally. Thanks!
> Add check for docker-desktop (MacOS) in startup

- newsfragments/1120.bugfix
- telepresence/proxy/deployment.py
Thanks for this wonderful tool! enjoying it so far :), but found a problem
Having CPU limit on telepresence pod causes noticeable latency increasing when there is a lot of simultaneously connections being proxied by telepresense. I observed almost 4X faster with my case( proxying a lot of connections) by disabling CPU limit. 
For latency sensitive applications, turning off CPU limit is sort of what's being suggested give the current kubernetes status. Thinking telepresense is one of the type.
> remove cpu resource limit

- newsfragments/1139.bugfix
- telepresence/startup.py
Previously called `/apis` endpoint which lists all resources in the cluster can be secured making it impossible to determine if the actual cluster is Openshift. In such a case Telepresence rolls back to `kubectl` and assumes `Deployment` is used rather than `DeploymentConfig` which is commonly used in Openshift.
The proposed solution calls Openshift-specific endpoint and based on the
response decides which cli tool to use.
Fixes #1139
> fix: calls /users endpoint to determine if oc should be used

- .editorconfig
- newsfragments/1148.bugfix
- telepresence/runner/runner.py
When running tel in WSL on Windows 10, Docker can't access `/tmp`. This adds an exception case for WSL, changing the tmp path.
> Use correct tmp dir when inside WSL

- k8s-proxy/Dockerfile.no_runasany_perms
the generated image will no longer fail due to missing privileges in secured/restrictive ocp or k8s environments
Also, the image is Centos/Rhel based, the usual base images for ocp (which also makes it bigger unfortunately: ~445Mb)
It's for the security focused envs, willing to trade the bigger size for solving issues like #875
PS: more explanations inside the file.
> new proxy image which solves the UID runAs issues with sshd

- newsfragments/1161.bugfix
- telepresence/outbound/local.py
Adds the `TELEPRESENCE_TEST_HOSTNAME` environment variable so that `test_hostname` can be changed as needed.
Also changes the default value of `test_hostname` to `kubernetes.default`.
> Fixes #1161

- newsfragments/1190.bugfix
- telepresence/startup.py
When a user is specifying a context, it may mean he is working outside the default context. If this is the case and the default context is not using the same versions that the context he will be working in, then the way this is currently written is checking the wrong versions (and failing, if the default context is failing).
This set's the context immediately after finding which `prelim_command` should be used. Thus, all subsequent checks will be checking the correct context versions.
---
```shell
```
- The other checks for your PR will succeed immediately without testing anything. They rely on Datawire …
> Ensure context is passed with all prelim_command

- newsfragments/1201.bugfix
- telepresence/outbound/vpn.py
As detailed in #1201, node.spec.podCIDR is not a reliable source for CIDR's being used. I have updated the podCIDRs function to use get the pod IP's if no CIDRs are found from the node.spec.
> Use pod IP's if no CIDRs can be found from the node spec

- docs/SUMMARY.md
- docs/tutorials/java.md
- docs/tutorials/kubernetes-client-libs.md
- newsfragments/1245.misc
Hi!
I created a separate page for client libraries and moved Java example to there. Also prepared a Python example with officially supported Kubernetes Python library and documented the process.
The image I have used as an example is based on a [repo](https://github.com/gurayyildirim/python-kubernetes-get-info/) I created for this example.
Related to #1245
> 1245 users want to use a kubernetes client in a swapped container

- docs/reference/limitations.md
As far as I see https://github.com/telepresenceio/telepresence/issues/462#issuecomment-376244255 , limitation on EC2 described at #462 was solved >=0.76 . So I delete statements about that limitations in documents.
> Delete statements about limitation on EC2 in documents

- docs/howto/golang.md
- docs/internal/demo-script.txt
- docs/reference/proxying.md
- docs/tutorials/docker.md
- docs/tutorials/kubernetes-client.md
- docs/tutorials/kubernetes.md
As of 1.18, `kubectl run` only creates pods. Rather than document the different behavior between versions, update the docs to always create deployments with `kubectl create deployment` which is compatible with all versions of `kubectl`.
Intended to address #1297 from a docs perspective 
TODO
> Fix doc compatibility with kubectl >= 1.18

- telepresence/proxy/__init__.py
- telepresence/proxy/deployment.py
As of kube 1.18, `kubectl run` is no longer capable of creating a deployment. This commit switches to supplying deployment yaml to `kubectl create -f` to ensure compatibility with all supported versions of kubectl. If `--expose` is specified, `kubectl expose` will be used to create a service.
Note that the yaml specifies `apiVersion: apps/v1`, which is compatible with kube >= 1.9.
Fixes #1297
> Create deployments with `kubectl create` for compatibility with kubectl 1.18

- k8s-proxy/resolver.py
- k8s-proxy/test_resolver.py
- newsfragments/560.misc
Add support of xxx.yyy.zzz.svc kube addresses DNS resolution, on top of
already supported "service" and "service.namespace".
This is required to handle Strimzi kafka auto-generated addresses for
example (see https://github.com/strimzi/strimzi-kafka-operator/issues/2656).
> Handle more kube DNS resolution formats

- Makefile
When running `make virtualenv` on macos (10.14.6, python3 installed via homebrew), the install of sshuttle from source results in the following error when it attempts to install setuptools_scm:
```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to
get local issuer certificate (_ssl.c:1076) -- Some packages may not
be found!
```
Full failure in a gist: https://gist.github.com/marun/4c2ff72b3b6db9db235e39f01b77b79e
Installing setuptools_scm in the virtualenv before attempting to install sshuttle works around the issue. Is there a less hacky way to fix this?
> Fix broken virtualenv install on macos

- newsfragments/1176.bugfix
- telepresence/runner/runner.py
It falls back to the old value if `/mnt/c` is not available.
Fixes #1176
Fixes #1254
Fixes #1335
> WSL: use a temp dir that exists on Debian/Ubuntu WSL

- Makefile
- tests/cluster/parameterize_utils.py
- tests/cluster/test_endtoend.py
- Skip also-proxy cluster tests for local clusters. We should test
`--also-proxy` in a less end-to-end manner elsewhere, e.g., by
seeing what arguments we're passing to `sshuttle`.
- Skip a probe's remaining tests when the probe fails. Don't fail those
tests, as that generates a lot of noise from `pytest` that gets in the
way of debugging the real failure.
- Make the virtualenv more quietly. Avoid lots of noise in CI.
> Make Telepresence development a little cleaner

- newsfragments/1380.bugfix
- telepresence/outbound/vpn.py
With minikube some of the system pods (e.g. etcd) are configured to have the same IP as minikube external endpoint. This results in podCIDRs=128.0.0.0/1 which breaks network.
Fixes #1380
> Do not proxy local cluster external IP

- k8s-proxy/forwarder.py
- k8s-proxy/resolver.py
- newsfragments/1385.feature
- telepresence/proxy/__init__.py
- telepresence/proxy/deployment.py
When --also-proxy hostname (not IP) is specified with local cluster, this patch makes DNS proxy to resolve that name (and subdomains) via cluster DNS. In my use case this makes it possible to properly handle DNS resolution for Minikube ingresses.
> Support resolving additional host names via local cluster

- telepresence/proxy/proxy.py
There's a straightforward bug with preexisting variable `name` being overwritten by the loop.
> Fix broken also-proxy parameter handling

- docs/reference/methods.md
- docs/reference/proxying.md
- newsfragments/1440.misc
Updated the "Proxying methods" section of the docs with a line specifying how to use --also-proxy with multiple hosts.
Closes #1440
> added documentation for specifying multiple hosts to also-proxy

- docs/announcing-telepresence-2.html
This commit removes unneeded bullet points, as they are rendered double (because of `<li>`).
I'm super excited about this announcement! Is the code already open? I would love to contribute!
> fix(docs): cleans up Telepresence 2 announcement

- docs/howto/volumes.md
As observed here:
- https://datawire-oss.slack.com/archives/CAUBBJSQZ/p1602485941085200
- https://datawire-oss.slack.com/archives/CAUBBJSQZ/p1605720784195500
a permission denied when trying to write to a volume can be resolved by this workaround.
> Explain how to acquire a privileged image when facing a write permission error

- docs/tutorials/docker.md
- docs/tutorials/hello-world.yaml
resolves #1409
- Replaced `kubectl create` and `kubectl expose` commands with a manifest that creates the deployment and service, with port info included in the deployment, the lack of which broke the tutorial.
- Made a few minor revisions across the doc
- After this is merged I'll go back and review the other tutorials, assuming they all need to be updated to use this manifest.
> Update Docker tutorial, add hello-world manifest

- newsfragments/1476.bugfix
- telepresence/outbound/setup.py
[`iptables --list` will occasionally hang](https://serverfault.com/questions/286422/iptables-hangs-when-listing-rules) while performing a reverse lookup for IP addresses. As it's just a sanity check, the lookup isn't needed.
> Prevent iptables --list from hanging on reverse lookup

- telepresence/proxy/operation.py
- tests/local/test_unit.py
Swap Deplyment fails on Deployments using startupProbes. This PR removes the startup Probe from swapped deployment as well 
---
```shell
```
> Attaching a debugger to the process running under Telepresence no longer causes the …
> Adding StartupProbe to probes to be deleted

- pkg/client/daemon/outbound_linux.go
This fix affects only unix systems where `systemd.resolved` isn't
configured correctly.
> Ensure that only non-qualified names traverse the DNS search-pathThallgren/dns weirdness

- CHANGELOG.md
- pkg/client/daemon/outbound.go
- pkg/client/daemon/outbound_darwin.go
- pkg/client/daemon/outbound_linux.go
- pkg/client/daemon/resolved_linux.go
This PR addresses the intricate problem that Docker on MacOS (and
possibly on other platforms as well) overrides the the DNS search. It
uses the DNS-resolver and everything else works (including
NAME.NAMESPACE). It's just the DNS search that gets overridden. The
Docker dns-search can however be configured, either by passing options
to the invocation or by modifying the Docker config. Only problem is,
that the Telepresence search path changes dynamically. A fix for
that problem is to introduce a static fake domain (here named
"tel2-search"), which, when queried, will replace itself with the
dynamic search path.
> Add fake domain that can be used as varying search-path.

- CHANGELOG.md
- pkg/client/connector/install.go
- pkg/client/connector/testdata/addAgentToDeployment/tc-11.input.yaml
- pkg/client/connector/testdata/addAgentToDeployment/tc-11.output.yaml
When we are selecting which container the agent for an intercept should be installed on, if we see a container that has no containerPorts, we automatically select that container.  While there are use cases where we do indeed want to select that container, we should make sure there aren't any better fits in the container list by seeing if there's a container where the containerPort matches the targetPort. 
See the test yaml I added for an example of this problem.
> Handle port-less containers better

- rpc/common/version.pb.go
- rpc/common/version.proto
In particular, explain what api_version is, since that was never clear to me (until today's spelunk through the edgectl code).
> [v2] version.proto: Add more doc comments

- CHANGELOG.md
- pkg/client/connector/outbound.go
Signed-off-by: Thomas Hallgren <thomas@datawire.io>
> Don't auto-skip mapping of kube-* and ambassador namespaces

- CHANGELOG.md
- pkg/client/connector/install.go
- pkg/client/connector/install_actions.go
- pkg/client/connector/install_test.go
- pkg/client/connector/testdata/addAgentToDeployment/mp-tc-1.input.yaml
- pkg/client/connector/testdata/addAgentToDeployment/mp-tc-1.output.yaml
When a TargetPort field is missing, the target port defaults to the
value of the Port field. This commit ensures that this case is handled
correctly.
> Handle services that have ports declared without a TargetPort field

- CHANGELOG.md
- pkg/client/connector/install.go
- pkg/client/connector/traffic_manager.go
This is a fix I believe for the error we have been seeing transiently in our tests that looks something like this: 
```   
--- FAIL: TestTelepresence/TestC_Uninstall (18.77s)
--- FAIL: TestTelepresence/TestC_Uninstall/Uninstalls_all_agents (6.97s)
...
multi.go:60: level="info" msg="multiple errors:\n  Operation cannot be fulfilled on deployments.apps \"with-probes\": the object has been modified; please apply your changes to the latest version and try again\n  Operation cannot be fulfilled on deployments.apps \"with-probes\": the object has been modified; please apply your changes to the latest version and try again\n" stream="stderr"
telepresence_test.go:589: level="info" msg="command terminated [\"telepresence\" \"uninstall\" \"--namespace\" \"telepresence-17500\" \"--all-agents\"]" …
```
> [v2] Uninstall once per deployment instead of per agent

- CHANGELOG.md
- pkg/client/cli/telepresence_test.go
- pkg/client/connector/install_test.go
- pkg/client/connector/intercept.go
- pkg/client/connector/k8s_cluster.go
- pkg/client/connector/k8s_config.go
- pkg/client/connector/traffic_manager.go
This changes the behavior when encountering an unmapped namespace for
the following commands:
- `list` returns an empty list
- `intercept` returns a NO_ACCEPTABLE_DEPLOYMENT error.
- `uninstall --agent` returns an "unable to find a deployment" error.
> Ensure that connector only acts on mapped namespaces.

- CHANGELOG.md
- pkg/client/daemon/nat/route.go
- pkg/client/daemon/nat/route_darwin.go
- pkg/client/daemon/nat/route_darwin_test.go
- pkg/client/daemon/nat/route_linux.go
- pkg/client/daemon/nat/route_test.go
- pkg/client/daemon/outbound.go
So I think this issue only affects us when people use externalNames where the lookupIP includes an IPv6 address.  This results in routes that have an IP that is IPv6 but our newRouteMessage only supported an IPv4 RTAX_GATEWAY and similarly our pfctl rules only worked for IPv4.  This adds support for both of those.
example of what some pfctl rules look like after they are written:
```
rdr pass on lo0 inet proto tcp from any to 10.43.223.167 port = 80 -> 127.0.0.1 port 62772
rdr pass on lo0 inet proto tcp from any to 10.43.223.167 port = 443 -> 127.0.0.1 port 62772
rdr pass on lo0 inet proto tcp from any to 10.43.233.56 port = 443 -> 127.0.0.1 port 62772
rdr pass on lo0 inet proto tcp from any to 10.43.244.24 port = 8080 -> 127.0.0.1 port 62772
rdr pass on lo0 inet proto tcp from any to …
```
> [v2] Fix bug where IPv6 routes broke all pfctl rule writes

- CHANGELOG.md
- k8s/echo-w-subdomain.yaml
- pkg/client/cli/telepresence_test.go
- pkg/client/connector/outbound.go
- pkg/client/daemon/outbound.go
- pkg/client/daemon/outbound_linux.go
This PR fixes two things:
1. Pods with a `hostname` and/or `subdomain` entry didn't get the `namespace` appended.
2. The DNS resolver was unable to resolve `<hostname>.<subdomain>.<namespace>` entries.
Some improvements were also made to the `telepresence_test.go` to ensure that commands 
can be limited with respect to timeouts and that the execution uses the `dexec.CommandContext`
to get better logging.
> [v2] Fix incorrect DNS and route for pods with hostname and/or subdomain

- CHANGELOG.md
- pkg/client/config.go
- pkg/client/config_test.go
- pkg/client/connector/install.go
- pkg/client/connector/intercept.go
- pkg/client/connector/k8s_cluster.go
- pkg/client/connector/service.go
- pkg/client/connector/traffic_manager.go
- pkg/client/daemon/proxy/proxy.go
- pkg/filelocation/app.go
- pkg/filelocation/ctx.go
Adds a generic configuration ability which reads a `config.yml` file
stored under the users config directory. Files under the system config
directories will also be considered on platforms that supports this.
The config contains only timeouts at present but it's expected to grow.
> [v2] Add ability to configure timeouts (and future other things)

- CHANGELOG.md
- pkg/client/connector/k8s_cluster.go
- pkg/client/connector/service.go
Starting the k8s watchers in parallel with the kubectl port-forward
creates intermittent problems on some platforms (most notably
Minikube with Hyperkit). Deferring until the traffic-manager is
fully connected lessens the concurrency at connect time and that
makes the intermittent problem go away.
> [v2] Defer startup of k8s watchers

- CHANGELOG.md
- base-image/Dockerfile
- cmd/traffic/cmd/agent/agent.go
- pkg/client/cli/telepresence_test.go
- pkg/client/connector/install.go
- pkg/client/connector/intercept.go
Kubernetes puts things in the `/var/run/secrets/kubenetes.io` folder that are essential to get
access to when doing intercepts. So this folder must be available as a remote mount point
even though no `mountPoints` entry exists in the pod spec.
> [v2] Make /var/run/secrets/kubenetes.io available to mount remotely.

- .golangci.yml
- CHANGELOG.md
- go.mod
- go.sum
- pkg/client/cli/intercept_state.go
- pkg/client/cli/run.go
- pkg/client/cli/telepresence_test.go
- pkg/client/cmd_error.go
- pkg/client/connector/install_test.go
- pkg/client/daemon/dns/flush_linux.go
- pkg/client/daemon/nat/route.go
- pkg/client/daemon/nat/route_darwin.go
- pkg/client/daemon/nat/route_linux.go
We got a report of the https://github.com/datawire/dlib/pull/14 crash happening in a real telepresence install on CentOS 7, so pull in the fix from dlib.
And while we're at it, now that the bug is fixed, switch (most) everything over to dexec instead of os/exec.  I left `run.go` alone though, because it's pretty hairy.
> [v2] Upgrade dlib, consistently use dlib/dexec

- CHANGELOG.md
- base-image/Dockerfile
Addresses https://github.com/datawire/telepresence2-proprietary/issues/53
I built the image locally, `docker exec --rm -it --entrypoint=/bin/sh` it and checked that they have a new OpenSSL:
```console
/ $ for file in /lib/libssl.so.* /lib/libcrypto.so.*; do version=$(grep 'OpenSSL 1' $file); echo "$file: $version"; done
/lib/libssl.so.1.1: OpenSSL 1.1.1k  25 Mar 2021
/lib/libcrypto.so.1.1: OpenSSL 1.1.1k  25 Mar 2021
```
> Upgrade to a newer Alpine

- CHANGELOG.md
- pkg/client/connector/install.go
When refreshing the ReplicaSet pods, it was looking at all pods in the
namespace so if we had a pod that was terminating, the ki.findPod call
would error when it got to that pod. This has been fixed by only calling
findPod on pods that have the ReplicaSet name in their name.  This was
causing
TestTelepresence/TestB_Connected/TestG_SuccessfullyInterceptsReplicaSet
to be a little flakey.
Signed-off-by: Donny Yung <donaldyung@datawire.io>
> [v2] Fix ReplicaSet intercept race condition

- CHANGELOG.md
- pkg/client/connector/install_actions.go
I was testing some other workloads and noticed that I had not fully finished the install_actions.go changes to work with all types of ReplicaSets 🤦‍♂️  This fixes that.
The error:
```
(⎈ |donnyyung-0:stateful)➜  ~/go/telepresenceio git:(donnyyung/fix-rs-containerport) ✗ telepresence intercept rs-echo --port 3000
telepresence: error: rpc error: code = Unknown desc = PANIC: interface conversion: kates.Object is *v1.ReplicaSet, not *v1.Deployment
```
> Fixes containerPort bug when intercepting RS

- CHANGELOG.md
- pkg/client/connector/install.go
- pkg/client/connector/traffic_manager.go
This fixes the bug mentioned in https://github.com/telepresenceio/telepresence/issues/1625 . Pretty self-explanatory fix, but findMatchingServices should have _only_ been looking at the namespace we were trying to intercept in instead of looking at all namespaces (which caused collisions with services that shouldn't have been collisions).
> [v2] Make FindMatchingServices namespace-bound

- CHANGELOG.md
- go.mod
- go.sum
- k8s/client_rbac.yaml
- k8s/echo-easy.yaml
- k8s/echo-w-agent.yaml
- k8s/echo-w-subdomain.yaml
- k8s/rs-echo.yaml
- k8s/ss-echo.yaml
- pkg/client/cli/list.go
- pkg/client/cli/telepresence_test.go
- pkg/client/connector/install.go
- pkg/client/connector/install_actions.go
- pkg/client/connector/install_test.go
- pkg/client/connector/k8s_cluster.go
- pkg/client/connector/testdata/addAgentToStatefulSet/mp-ss-tc-0.input.yaml
- pkg/client/connector/testdata/addAgentToStatefulSet/mp-ss-tc-0.output.yaml
- pkg/client/connector/testdata/addAgentToStatefulSet/ss-tc-0.input.yaml
- pkg/client/connector/testdata/addAgentToStatefulSet/ss-tc-0.output.yaml
- pkg/client/connector/traffic_manager.go
- rpc/connector/connector.pb.go
- rpc/connector/connector.proto
This will enable users to intercept StatefulSet services, and largely builds on top of the ReplicaSet PR I merged last week, I've also cleaned up some functions + names that I introduced in that PR that weren't the best.  Would recommend a commit-by-commit review.
> [v2] Add support for StatefulSets 

- pkg/client/cli/telepresence_test.go
- pkg/client/logging/initcontext.go
- pkg/client/logging/rotatingfile.go
It was calling os.MkdirAll with the filepath.Dir of `fileName`, which is
*already* the basename, so the filepath.Dir of it was *always* just ".".
So rename the variables to hopefully make this clearer:
- fullPath → logfilePath
- dirName  → logfileDir
- fileName → logfileBase
> [v2] OpenRotatingLogFile: Fix the os.MkdirAll call

- pkg/client/connector/install.go
When introducing portNameOrNumber instead of just portName, I made an
error in the logic and it was checking if the annotations matched the
value of portNameOrNumber, even when that value is empty.  This fixes
the logic so that we only validate portNameOrNumber with the annotations
when it is non-empty
Signed-off-by: Donny Yung <donaldyung@datawire.io>
---
> Fix checkSvcSame when portNameOrNumber empty

- CHANGELOG.md
- pkg/client/connector/install_actions.go
hcp.PortName was correct when we were adding the agent but it is
hcp.HiddenName when we do an uninstall, so in the error log we should use the
input to be correct in both cases.
---
> [v2] Fix hcp error log

- CHANGELOG.md
- pkg/client/connector/install.go
- pkg/client/connector/install_actions.go
- pkg/client/connector/testdata/addAgentToWorkload/deployment-initializer.input.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-initializer.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-mp-tc-0.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-mp-tc-1.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-mp-tc-2.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-mp-tc-3.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-0.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-1.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-10.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-11.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-2.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-3.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-4.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-5.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-6.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-7.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-8.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/deployment-tc-9.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/replicaset-mp-tc-0.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/replicaset-tc-0.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/statefulset-mp-tc-0.output.yaml
- pkg/client/connector/testdata/addAgentToWorkload/statefulset-tc-0.output.yaml
Signed-off-by: Thomas Hallgren <thomas@datawire.io>
Don't generate port names longer than 15 characters.
> Ensure that we don't create port names longer than 15 characters.

- CHANGELOG.md
- DEVELOPING.md
- pkg/client/connector/install.go
- pkg/client/connector/k8s_cluster.go
There was a race condition in determining presence of the ambassador
namespace that was dependent on trying to create the namespace and
ignoring the error if the namespace existed.  This is an unneccesary
rbac escalation, so I have fixed that here.
Signed-off-by: Donny Yung <donaldyung@datawire.io>
> Better detect presence of ambassador namespace

- CHANGELOG.md
- pkg/client/connector/auth/login.go
- pkg/client/connector/auth/refresh.go
Occasionally, Telepresence decides to hammer the Ambassador Cloud auth server.  This fixes that.  I have tested it manually, but did not write an automated test yet.
> connector: Don't keep retrying if the access/refresh tokens are expired

- CHANGELOG.md
- pkg/client/connector/auth/login.go
- pkg/client/connector/service.go
This came up during smoke-testing of 2.2.1-rc.0.
> [v2] Fix `telepresence login` when there's an expired login

- pkg/client/connector/intercept.go
---
Regarding the issue https://github.com/telepresenceio/telepresence/issues/1697 there is a problem when trying to intercept a workload. That workload exists in multiple namespaces. When a workload is intercepted and there is another interception done, the new interceptions gets the env vars in a wrong way, getting the env vars from other namespace.
> fix: multiple agents running getting wrong agent when intercepts

- docs/macros.html
updated the macOS installation instruction from brew install cask osxfuse to brew install --cask osxfuse
---
```shell
```
- …
> Updated the brew installation instructions

- ci/setup-gcloud.sh
- environment-setup.sh
- gcloud CLI has changed how to authorize with docker
- brew CLI has changed how to install casks
> Update environment-setup script

- .github/stale.yml
I was looking for an outside-contributor PR, and none existed.  That didn't seem right!
Having stalebot close issues and PRs is just a jerk move.  Have it flag them stale, but don't close them.
> stalebot: Don't close issues or PRs, just mark them stale

- docs/_layouts/website/page.html
- docs/about.html
- docs/announcing-telepresence-2.html
- docs/case-studies/bitnami.html
- docs/case-studies/engel-volkers.html
- docs/case-studies/index.html
- docs/case-studies/iris-tv.html
- docs/case-studies/sight-machine.html
- docs/case-studies/verloop.html
- docs/community.html
- docs/index.html
This is solving the same thing as https://github.com/telepresenceio/telepresence/pull/1414 :
> As it stands, search engines are currently crawling our deploy previews from GitHub and indexing them, making the published telepresence.io website less valuable in their eyes due to the content duplication.
But is solving it in a different way: Adding `<link rel="canonical">` tags, so that Google knows which one is the non-duplicate.  This is the same solution as we use for getambassador.io previews.
> website: Add <link rel="canonical"> tags
